apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: kaspar
spec:
  ports:
    - name: cluster
      port: 7077
      targetPort: 7077
      nodePort: 30077
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
  selector:
    app.kubernetes.io/component: spark-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: kaspar
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: spark-master
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spark-master
    spec:
      containers:
        - name: spark-master-container
          image: kaspar-spark:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_MODE
              value: 'master'
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: 'no'
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: 'no'
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: 'no'
            - name: SPARK_SSL_ENABLED
              value: 'no'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: kaspar
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: spark-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spark-worker
    spec:
      containers:
        - name: spark-master-container
          image: kaspar-spark:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPARK_MODE
              value: 'worker'
            - name: SPARK_MASTER_URL
              value: 'spark://spark-master-svc:7077'
            - name: SPARK_WORKER_MEMORY
              value: '500m'
            - name: SPARK_WORKER_CORES
              value: '2'
            - name: SPARK_WORKER_WEBUI_PORT
              value: '8080'
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: 'no'
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: 'no'
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: 'no'
            - name: SPARK_SSL_ENABLED
              value: 'no'
